# Generated by Django 6.1.1 on 2026-09-18 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_productvariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, help_text='Shelf code.', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock in'), ('OUT', 'Stock out'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('reason', models.CharField(choices=[('RECEIPT', 'Goods received'), ('SALE', 'Sale'), ('RETURN', 'Customer return'), ('COUNT', 'Stock count'), ('DAMAGE', 'Damage or loss'), ('MANUAL', 'Manual correction')], default='MANUAL', max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive to add, Negative to remove.')),
                ('balance_after', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='Invoice or receipt number.', max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movments', to='catalog.productvariant')),
            ],
        ),
    ]
